# Generated by Django 6.0.6 on 2026-06-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido de la Carta')),
                ('unlock_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Desbloqueo')),
                ('created_by', models.CharField(default='Alejo', max_length=100, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha del Recuerdo')),
                ('media', models.FileField(blank=True, null=True, upload_to='memories/', verbose_name='Foto o Video')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], default='image', max_length=10, verbose_name='Tipo de Media')),
                ('spotify_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace de Spotify')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del Evento')),
                ('event_type', models.CharField(choices=[('birthday', 'Cumpleaños'), ('anniversary', 'Aniversario'), ('christmas', 'Navidad'), ('custom', 'Personalizado')], default='custom', max_length=20)),
                ('month', models.IntegerField(verbose_name='Mes')),
                ('day', models.IntegerField(verbose_name='Día')),
                ('last_sent_year', models.IntegerField(default=0, verbose_name='Último Año de Notificación Enviada')),
                ('recipients', models.TextField(default='alejosierra656@gmail.com,yelenabreidy@gmail.com', verbose_name='Correos de Destinatarios (separados por comas)')),
            ],
        ),
    ]
