# Generated by Django 6.0.6 on 2026-06-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Meta o Sueño')),
                ('category', models.CharField(choices=[('viaje', '✈️ Viajes'), ('aventura', '🌊 Aventuras'), ('romantico', '❤️ Romántico'), ('comida', '🍕 Comida'), ('cultura', '🎨 Cultura'), ('hogar', '🏠 Hogar'), ('otro', '✨ Otro')], default='otro', max_length=20)),
                ('is_completed', models.BooleanField(default=False, verbose_name='¿Completado?')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('created_by', models.CharField(default='Alejo', max_length=100, verbose_name='Propuesto por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emoji', models.CharField(blank=True, default='🌟', max_length=10, verbose_name='Emoji')),
            ],
            options={
                'ordering': ['is_completed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoveNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=400, verbose_name='Nota de Amor')),
                ('color', models.CharField(choices=[('pink', 'Rosa'), ('lavender', 'Lavanda'), ('peach', 'Durazno'), ('mint', 'Menta'), ('yellow', 'Amarillo')], default='pink', max_length=20)),
                ('created_by', models.CharField(default='Alejo', max_length=100, verbose_name='De')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotation', models.FloatField(default=0.0, verbose_name='Rotación (grados)')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_playlist_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL de Playlist/Canción de Spotify')),
                ('our_song_title', models.CharField(blank=True, default='Nuestra Canción', max_length=200, verbose_name='Nombre de la Canción')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Espacio',
                'verbose_name_plural': 'Configuración del Espacio',
            },
        ),
    ]
