# Generated by Django 6.0.6 on 2026-06-15 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_bucketitem_lovenote_spacesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketitem',
            name='category',
            field=models.CharField(choices=[('viaje', 'Viajes'), ('aventura', 'Aventuras'), ('romantico', 'Romántico'), ('comida', 'Comida'), ('cultura', 'Cultura'), ('hogar', 'Hogar'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='bucketitem',
            name='emoji',
            field=models.CharField(blank=True, default='Sparkles', max_length=100, verbose_name='Icono'),
        ),
        migrations.CreateModel(
            name='MemoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='memories/photos/', verbose_name='Archivo')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], default='image', max_length=10, verbose_name='Tipo de Media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='moments.memory', verbose_name='Recuerdo')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
